services:
  - type: web
    name: superstars
    runtime: docker
    envVars:
      - key: CACHE_TTL_SECONDS
        value: 21600
      - key: DATABASE_URL
        sync: false
      - key: GITHUB_TOKEN
        sync: false
